---
title: "KOGPSY"
description: |
  Welcome to the website for *Kognitionspsychologie II* FS22 ([23263-02](https://vorlesungsverzeichnis.unibas.ch/de/home?id=263194))
  
  Instructor: [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), University of Basel
  
  **Last updated:** `r format(Sys.time(), "%a %b %d %X %Y")`
  
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

![Thinking, feeling, willing are simply words we use to describe different ways of using one's brain! <span>Photo by <a href="https://unsplash.com/@jessemartini?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jesse Martini</a> on <a href="https://unsplash.com/s/photos/brain?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>](photos/jesse-martini-Iod3vdjKE1E-unsplash.jpg)

# Session information

Sessions take place Tuesdays, 10.15-11.45. 

::: l-body
| # | Date     | Topic                         | Slides |
|---| ---------|-------------------------------|--------|
| 1 | 02.03.2021 | [Session 1: Introduction](session1.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session1.pdf)|
| 2 | 09.03.2021 | [Session 2: What is intelligence?](session2.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session2.pdf)|
| 3 | 16.03.2021 | [Session 3: Intelligence: Nature & Nurture](session3.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session3.pdf)|
| 4 | 23.03.2021 | [Session 4: Space](session4.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session4.pdf)|
| 5 | 30.03.2021 | [Session 5: Number](session5.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session5.pdf)|
| 6 | 06.04.2021 | [Session 6: Language](session6.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session6.pdf)|
| 7 | 13.04.2021 | [Session 7: Facts](session7.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session7.pdf)|
| 8 | 20.04.2021 | [Session 8: Emotion](session8.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session8.pdf)|
| 9 | 27.04.2021 | [Session 9: Motivation](session9.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session9.pdf)|
|10 | 04.05.2021 | [Session 10: Consciousness](session10.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session10.pdf)|
|11 | 11.05.2021 | [Session 11: What's next?](session11.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session11.pdf)|
|12 | 18.05.2021 | [Session 12: Q&A](session12.html) | [pdf](https://github.com/matarui/kogpsy/raw/main/docs/presentations/KOGPSY_session12.pdf)|
|13 | 25.05.2021 | [Exam](exam.html) | |
:::

# What is this course about?

This course aims to give a broad introduction to central topics in psychological science, with a focus on mechanistic explanations of cognition, emotion, and motivation. 

# What can you expect to learn?

By completing the course you can expect to...

- learn about central theories and models in key areas of psychology
- become familiarized with common methods used in the psychological sciences
- learn about examples of applications of psychological science to real-world contexts
- reflect about the need for pluralistic explanations of human behavior

# How should you use this website?

This website is designed to help course participants get an overview of the course and access most course materials (e.g., recommended background readings and videos, additional non-mandatory readings). A number of other resources, however, are available. An [FAQ](https://adam.unibas.ch/goto_adam_crs_1008695.html) forum is available on ADAM. Any recordings of the sessions will be made available on [SWITCHtube](https://tube.switch.ch/channels/d4bc1931). Information about the exam is available on the [Exam](exam.html) tab on this webpage.  

Course materials, such as readings or suggested preparation exercises, will be made available about one week before each session. Videos of the online sessions and associated slides will be posted **after** each session. 

# Video recordings and SWITCHtube

Any recordings will be made available after each session on [SWITCHtube](https://tube.switch.ch/channels/d4bc1931). All recordings will be deleted at the end of the semester. According to University of Basel's [regulations](https://www.unibas.ch/dam/jcr:9e482656-e333-42ec-bbd3-4639dedd3dc7/R_Ton-Bildaufnahmen_00.pdf) these **recordings** are for **personal use** only and should **not be further distributed** in any form.  
